-- Verschiebt die bisherigen Angebotsfelder aus centers in services und
-- center_services. Vorhandene Freitextwerte aus leistungen bleiben als
-- eigene Angebotsnamen erhalten.
BEGIN;

CREATE TABLE services (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    beschreibung text NOT NULL DEFAULT ''
);

CREATE TABLE center_services (
    center_id integer NOT NULL REFERENCES centers(id) ON DELETE CASCADE,
    service_id integer NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    PRIMARY KEY (center_id, service_id)
);

INSERT INTO services (name)
VALUES
    ('Pflegestützpunkt'),
    ('Pflegeberatung'),
    ('Wohnberatung'),
    ('Demenzberatung'),
    ('Angehörigenberatung'),
    ('Betreuungsberatung')
ON CONFLICT (name) DO NOTHING;

INSERT INTO services (name)
SELECT DISTINCT btrim(leistungen)
FROM centers
WHERE btrim(leistungen) <> ''
ON CONFLICT (name) DO NOTHING;

INSERT INTO center_services (center_id, service_id)
SELECT c.id, s.id
FROM centers AS c
CROSS JOIN LATERAL (
    VALUES
        ('Pflegestützpunkt', c.pflegestuetzpunkt),
        ('Pflegeberatung', c.pflegeberatung),
        ('Wohnberatung', c.wohnberatung),
        ('Demenzberatung', c.demenzberatung),
        ('Angehörigenberatung', c.angehoerigenberatung),
        ('Betreuungsberatung', c.betreuungsberatung)
) AS offered(service_name, is_offered)
JOIN services AS s ON s.name = offered.service_name
WHERE offered.is_offered
ON CONFLICT DO NOTHING;

INSERT INTO center_services (center_id, service_id)
SELECT c.id, s.id
FROM centers AS c
JOIN services AS s ON s.name = btrim(c.leistungen)
WHERE btrim(c.leistungen) <> ''
ON CONFLICT DO NOTHING;

ALTER TABLE centers
    DROP COLUMN pflegestuetzpunkt,
    DROP COLUMN pflegeberatung,
    DROP COLUMN wohnberatung,
    DROP COLUMN demenzberatung,
    DROP COLUMN angehoerigenberatung,
    DROP COLUMN betreuungsberatung,
    DROP COLUMN leistungen;

COMMIT;
