-- Initiales Datenbankschema für das Pflegestellenverzeichnis:
--   centers         Stammdaten der Pflegestellen
--   services        zentrale Liste der angebotenen Leistungen
--   center_services Zuordnung von Pflegestellen zu ihren Leistungen (n:m)
--
-- PostgreSQL im Docker-Image führt diese Datei nur beim erstmaligen
-- Initialisieren eines leeren Datenbank-Volumes automatisch aus. Für spätere
-- Schemaänderungen bestehender Datenbanken sind separate Migrationen
-- vorzusehen.
--
-- In centers entspricht id unserer stabilen unsere_id; zqp_id ist der
-- externe Schlüssel für Datenabgleiche. bundesland enthält den zweistelligen
-- ISO-Code. Telefonnummern bleiben Text, damit Sonderzeichen und mehrere
-- Nummern erhalten bleiben. aktiv kennzeichnet, ob eine Pflegestelle aktiv
-- ist, statt sie zu löschen. quelle_updated_at speichert den
-- Aktualisierungszeitpunkt aus der Datenquelle.

CREATE TABLE IF NOT EXISTS centers (
    id integer PRIMARY KEY,
    zqp_id varchar(32) UNIQUE,
    name text NOT NULL DEFAULT '',
    bundesland char(2) NOT NULL DEFAULT '',
        plz char(5) NOT NULL DEFAULT ''
        CHECK (btrim(plz) = '' OR btrim(plz) ~ '^[0-9]{5}$'),
    ort text NOT NULL DEFAULT '',
    adresse text NOT NULL DEFAULT '',
    email text NOT NULL DEFAULT '',
    telefon text NOT NULL DEFAULT '',
    website text NOT NULL DEFAULT '',
    latitude double precision
        CHECK (latitude BETWEEN 47 AND 56),
    longitude double precision
        CHECK (longitude BETWEEN 5 AND 16),
    aktiv boolean NOT NULL DEFAULT true,
    quelle_updated_at timestamp,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS services (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    beschreibung text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS center_services (
    center_id integer NOT NULL REFERENCES centers(id) ON DELETE CASCADE,
    service_id integer NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    PRIMARY KEY (center_id, service_id)
);

CREATE INDEX IF NOT EXISTS idx_center_services_service_id
    ON center_services (service_id);

INSERT INTO services (name)
VALUES
    ('Pflegestützpunkt'),
    ('Pflegeberatung'),
    ('Wohnberatung'),
    ('Demenzberatung'),
    ('Angehörigenberatung'),
    ('Betreuungsberatung')
ON CONFLICT (name) DO NOTHING;
